### ISSUE TITLE
RTL languages not supported

### ISSUE THREAD

**Issue by peylight** [CarnetApp/CarnetDocumentation#104]
Hello
CarnetAndroid have no good view in Right To Left Languages.
Please fix RTL problems.

**Comment by PhieF** [comment]
Tranferring since this problem is for the whole Carnet project

**Comment by peylight** [comment]
Thanks, and don't forgot Bidirectional text please...
https://www.w3.org/International/articles/inline-bidi-markup/

**Comment by PhieF** [comment]
bidirectionnal might be difficult, here what I have right now, what do you think ?
![Capture d’écran de 2020-05-12 09-42-00](https://user-images.githubusercontent.com/26841885/81688586-f4e6fb80-9459-11ea-9048-b3b648fcfb7e.png)

**Comment by peylight** [comment]
Seems good, Thanks

**Comment by peylight** [comment]
And the RTL title in the main page should be better show.

**Comment by PhieF** [comment]
I've just released a new version 0.22.0

RTL languages are now supported, even if not perfect it's far better, I will improve it in next releases ! 
Thanks !
