### ISSUE TITLE
Keep Import didn't work + Design flaw

### ISSUE THREAD

**Issue by JokerGermany** [CarnetApp/CarnetDocumentation#53]
Ubuntu Mate 18.04.2 64 Bit
Linux 64 Bit - Carnet 16.0

When Importing Google Keep and there are to many directorys i get this
![Keep Import](https://user-images.githubusercontent.com/30293477/58575908-64f97300-8243-11e9-8e84-a3e90ef3865b.png)
(BTW: I liked the old menu, which was using the OS.)
When I have chosen the right directory and click on "pick folder" it seems like nothing happen

**Comment by drw72** [comment]
Ubuntu19.04 64 Bit
Linux 64 Bit - Carnet 16.2

I get the same thing.

**Comment by WarpinWolf** [comment]
+1

**Comment by PhieF** [comment]
Next version will see a new importer, so I'm closing it for now, you can reopen it if you see no improvements in next version ! thanks for your reports!
