### ISSUE TITLE
[Feature Request] List View Setting

### ISSUE THREAD

**Issue by Nesh108** [CarnetApp/CarnetDocumentation#88]
Hello!

I have discovered this nifty tool when looking for alternatives to Notion.
I mainly use it to take quick notes, so I thought that having something straight into my own NextCloud was awesome (especially with the mobile app!).

I have only 1 request:

Is it possible to change the view (both desktop/web and mobile) to a list with the keywords visible? 

Something like this:

![image](https://user-images.githubusercontent.com/1250305/72497131-a7210480-3866-11ea-8c45-7eb966ca8710.png)

Instead of:

![Screen Shot 2020-01-16 at 13 49 23](https://user-images.githubusercontent.com/1250305/72497268-0b43c880-3867-11ea-83e2-ad88eaba34ac.png)

Let me know :)

**Comment by PhieF** [comment]
Hi,

List view will be implemented soon (i guess, I plan it)
